### ISSUE TITLE
Use of undeclared identifier 'assert'

### ISSUE THREAD

**Issue by bennigraf** [arturoc/ofxGstRTP#2]
Hi there!

I just tried to build "example-all" from the ofxGstRtp-package. After having to solve many many dependencies ;-) I came to the following point:

In ofxOscMessage.cpp I get the error "Semantic Issue: Use of undeclared identifier 'assert'". 

The Osc examples coming with OF build fine on their own, though, so I don't get whats going on here...
